FROM jjpr/blender-mayavi-jupyter:latest

RUN mkdir /data/examples/images
COPY Equation_To_Object_Instructions.ipynb /data/examples/
COPY images/ruffle_equation.png /data/examples/images/
COPY images/wrapped_ruffle.png /data/examples/images/
COPY images/printed.png /data/examples/images/
COPY images/saddle_grapher.png /data/examples/images/
COPY solidify.py /data/examples/

